<?php
/**
 * @file
 * Declare the settings for the chi layout.
 */

/**
 * Plugin definition for the chi layout.
 */
$plugin = array(
  'title' => t('Chi'),
  'category' => t('Paddle Layouts'),
  'icon' => 'paddle_chi.png',
  'theme' => 'paddle_chi',
  'css' => 'paddle_chi.css',
  'regions' => array(
    'full_a' => t('A'),
    'full_b' => t('B'),
    'nested_6_c' => t('C'),
    'nested_6_d' => t('D'),
    'nested_4_e' => t('E'),
    'nested_4_f' => t('F'),
    'nested_4_g' => t('G'),
    'nested_3_h' => t('H'),
    'nested_3_i' => t('I'),
    'nested_3_j' => t('J'),
    'nested_3_k' => t('K'),
    'full_l' => t('L'),
    'nested_6_m' => t('M'),
    'nested_6_n' => t('N'),
    'nested_4_o' => t('O'),
    'nested_4_p' => t('P'),
    'nested_4_q' => t('Q'),
    'nested_3_r' => t('R'),
    'nested_3_s' => t('S'),
    'nested_3_t' => t('T'),
    'nested_3_u' => t('U'),
    'full_v' => t('V'),
    'nested_6_w' => t('W'),
    'nested_6_x' => t('X'),
    'nested_4_y' => t('Y'),
    'nested_4_z' => t('Z'),
    'nested_4_aa' => t('AA'),
    'nested_3_ab' => t('AB'),
    'nested_3_ac' => t('AC'),
    'nested_3_ad' => t('AD'),
    'nested_3_ae' => t('AE'),
    'full_af' => t('AF'),
    'nested_6_ag' => t('AG'),
    'nested_6_ah' => t('AH'),
    'nested_4_ai' => t('AI'),
    'nested_4_aj' => t('AJ'),
    'nested_4_ak' => t('AK'),
    'nested_3_al' => t('AL'),
    'nested_3_am' => t('AM'),
    'nested_3_an' => t('AN'),
    'nested_3_ao' => t('AO'),
  ),
);
