<?php
/**
 * @file
 * paddle_vub_client_scald.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function paddle_vub_client_scald_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_published_image'.
  $field_bases['field_published_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_published_image',
    'indexes' => array(
      'sid' => array(
        0 => 'sid',
      ),
    ),
    'locked' => 0,
    'module' => 'paddle_scald_atom_field',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'paddle_scald_atom',
  );

  // Exported field_base: 'field_vub_server_sid'.
  $field_bases['field_vub_server_sid'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_vub_server_sid',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
