<?php
/**
 * @file
 * Install, uninstall, update and schema hooks for Paddle CIRRO Test.
 */

/**
 * Implements hook_enable().
 */
function paddle_cirro_test_enable() {
  // Creates the body field for paddle_cirro_pages since SimpleTest does not
  // care about field_instance_sync.
  // @TODO Fix this in the Field Instance Sync module.
  $field_instance = array(
    'bundle' => 'paddle_cirro_page',
    'default_value' => array(
      0 => array(
        'summary' => '',
        'mee' => array(
          'resource_manager' => array(
            0 => array(
              'weight' => 0,
            ),
          ),
        ),
        'value' => '',
        'format' => 'full_html',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'diff_standard' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'listing_teaser' => array(
        'label' => 'hidden',
        'module' => 'paddle_landing_page',
        'settings' => array(
          'trim_length' => 160,
        ),
        'type' => 'paddle_landing_page_summary_or_trimmed_plain_text',
        'weight' => 0,
      ),
      'listing_title' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'node_content_pane_full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'node_content_pane_summary' => array(
        'label' => 'hidden',
        'module' => 'paddle_landing_page',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'paddle_landing_page_summary_or_trimmed_plain_text',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'full_html' => 'full_html',
          'plain_text' => 0,
        ),
        'allowed_formats_toggle' => 1,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'full_html' => array(
              'weight' => -10,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
          ),
        ),
      ),
      'context' => 'debug',
      'display_summary' => 1,
      'dnd_enabled' => 0,
      'field_instance_sync' => 1,
      'mee_enabled' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 0,
    ),
  );

  field_create_instance($field_instance);
}
