<?php

/**
 * Implements hook_views_data().
 */
function views_roles_views_data() {
  $data = array();
  // ----------------------------------------------------------------
  // role table -- basic table information.

  // Define the base group of this table. Fields that don't
  // have a group defined will go into this field by default.
  $data['role']['table']['group'] = t('Role');

  // Advertise this table as a possible base table
  $data['role']['table']['base'] = array(
    'field' => 'rid',
    'title' => t('Role'),
    'weight' => -10,
    'defaults' => array(
      'field' => 'name',
    ),
  );

  // ----------------------------------------------------------------
  // role table -- fields

  // rid
  $data['role']['rid'] = array(
    'title' => t('Rid'),
    'help' => t('The role ID.'), // The help that appears on the UI,
    // Information for displaying the rid
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    // Information for accepting a rid as an argument
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
      'name field' => 'title', // the field to display in the summary.
      'numeric' => TRUE,
      'validate type' => 'nid',
    ),
    // Information for accepting a rid as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    // Information for sorting on a rid.
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  // Role name
  // This definition has more items in it than it needs to as an example.
  $data['role']['name'] = array(
    'title' => t('Name'), // The item it appears as on the UI,
    'help' => t('The role name.'), // The help that appears on the UI,
     // Information for displaying a title as a field
    'field' => array(
      'field' => 'name', // the real field. This could be left out since it is the same.
      'group' => t('Role'), // The group it appears in on the UI. Could be left out.
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
     ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    // Information for accepting a title as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  // Role weight
  $data['role']['weight'] = array(
    'title' => t('Weight'),
    'help' => t('The role weight'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_numeric',
    ),
  );
  return $data;
}