<?php
/**
 * @file
 * Declare the settings for the celebi layout.
 */

/**
 * Plugin definition for the celebi layout.
 */
$plugin = array(
  'title' => t('Celebi'),
  'category' => t('Paddle Layouts'),
  'icon' => 'paddle_celebi.png',
  'theme' => 'paddle_celebi',
  'css' => 'paddle_celebi.css',
  'regions' => array(
    'full_a' => t('A'),
    'nested_7_b' => t('B'),
    'nested_5_c' => t('C'),
    'bottom' => t('D'),
    'nested_6_e' => t('E'),
    'nested_6_f' => t('F'),
    'nested_4_g' => t('G'),
    'nested_4_h' => t('H'),
    'nested_4_i' => t('I'),
    'right' => t('J'),
  ),
);
