<?php
/**
 * @file
 * Declare the settings for the phi layout.
 */

/**
 * Plugin definition for the phi layout.
 */
$plugin = array(
  'title' => t('Phi'),
  'category' => t('Paddle Layouts'),
  'icon' => 'paddle_phi.png',
  'theme' => 'paddle_phi',
  'css' => 'paddle_phi.css',
  'regions' => array(
    'nested_9_a' => t('A'),
    'nested_3_b' => t('B'),
    'nested_3_c' => t('C'),
    'nested_3_d' => t('D'),
    'nested_3_e' => t('E'),
    'nested_3_f' => t('F'),
    'nested_3_g' => t('G'),
    'nested_3_h' => t('H'),
    'nested_3_i' => t('I'),
    'nested_3_j' => t('J'),
    'nested_3_k' => t('K'),
    'nested_3_l' => t('L'),
    'nested_3_m' => t('M'),
    'nested_3_n' => t('N'),
    'nested_3_o' => t('O'),
    'nested_3_p' => t('P'),
    'nested_3_q' => t('Q'),
    'nested_3_r' => t('R'),
    'full_s' => t('S'),
  ),
);
