<?php

/**
 * @file
 * Code for the Paddle VUB server module.
 */

/**
 * Implements hook_restws_format_info_alter().
 */
function paddle_vub_server_restws_format_info_alter(&$format_info) {
  $format_info['json']['class'] = 'PaddleVUBServerFormatJSON';
}

/**
 * Implements hook_restws_resource_info_alter().
 */
function paddle_vub_server_restws_resource_info_alter(&$resource_info) {
  $resource_info['node']['class'] = 'RestWSVUBNodeResourceController';
}

/**
 * Implements hook_paddle_content_manager_additional_fields().
 */
function paddle_vub_server_paddle_content_manager_additional_fields() {
  $menu_object = menu_get_object();
  if (isset($menu_object)) {
    if ($menu_object->type == 'news_item') {
      return array(
        'field_vub_force_publish',
      );
    }
  }
  return array();
}
